Don't delete temp branch in worker (#219)
Don't delete current branch in CI worker to avoid error:

```
mantis 0.3.26 => 0.3.27
[_tmp_master 49b19c7] temp version bump
 2 files changed, 2 insertions(+), 2 deletions(-)
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
✅ PR branch matches a clean version bump from master.
error: cannot delete branch '_tmp_master' used by worktree at '/home/runner/work/mantis/mantis'
Error: Process completed with exit code 1.
```