CI ensure version bump (#127)
Ensure that the package version in `pyproject.toml` has been updated in
every PR.

If not updated, fail the check.

```sh
Master version: 0.1.0
Current version: 0.1.0
Error: pyproject.toml version has not been updated!
Error: Process completed with exit code 1.
```